#!/usr/bin/env bash

# 📋 数据输入格式调整 - 快速操作指南

echo "🎯 港股舆情 - 数据格式调整完成"
echo "================================"
echo ""

echo "📊 调整内容:"
echo "✅ 将 /data 下的 JSON 格式转换为程序内部的 DataStreamSample 格式"
echo "✅ 创建 json_data_loader.py 数据加载模块"
echo "✅ 扩展 data_stream_sampler.py 添加 JSONDataStream 类"
echo "✅ 添加完整的使用文档和测试脚本"
echo ""

echo "📁 新增文件:"
echo "  1. json_data_loader.py (9.4K) - JSON 数据加载和转换模块"
echo "  2. test_json_format.py (7.7K) - 数据格式验证测试脚本"
echo "  3. JSON_FORMAT_GUIDE.md (8.1K) - 使用指南和 API 参考"
echo "  4. DATA_INPUT_FORMAT_SUMMARY.md (7.2K) - 调整总结文档"
echo ""

echo "📝 快速开始"
echo "==========="
echo ""

echo "1️⃣  验证数据格式转换是否正常:"
echo "   cd /Users/mac/sandbox/HKU/COMP7705"
echo "   python test_json_format.py"
echo ""

echo "2️⃣  在代码中使用真实数据:"
echo "   from json_data_loader import load_data_for_sampling"
echo "   samples = load_data_for_sampling()"
echo "   print(f'加载了 {len(samples)} 个样本')"
echo ""

echo "3️⃣  使用 JSON 数据流推送到采样器:"
echo "   from data_stream_sampler import JSONDataStream"
echo "   json_stream = JSONDataStream(sampler)"
echo "   json_stream.stream_from_json()"
echo ""

echo "4️⃣  运行完整演示 (包括 JSON 数据演示):"
echo "   python demo_online_testing.py"
echo "   # 选择演示 2️⃣ 或 8️⃣"
echo ""

echo "📊 数据格式映射"
echo "==============="
echo ""

echo "原始 JSON (sentiment_input_batch.json):"
echo "  ├─ text_id"
echo "  ├─ language"
echo "  ├─ title"
echo "  ├─ content"
echo "  ├─ stock_codes"
echo "  ├─ stock_names"
echo "  ├─ source_type"
echo "  ├─ source_name"
echo "  ├─ published_at"
echo "  └─ url"
echo ""

echo "程序内部格式 (DataStreamSample):"
echo "  ├─ sample_id ← text_id + 索引"
echo "  ├─ raw_text_id ← text_id"
echo "  ├─ text ← title + content"
echo "  ├─ language ← language"
echo "  ├─ stock_code ← stock_codes[0]"
echo "  ├─ source ← source_type"
echo "  ├─ source_name ← source_name"
echo "  ├─ timestamp ← published_at"
echo "  ├─ sampled_at (自动生成)"
echo "  ├─ confidence (默认值)"
echo "  └─ priority (默认值)"
echo ""

echo "✅ 完成清单"
echo "=========="
echo "✓ JSON 数据加载模块已创建"
echo "✓ 数据流转换已实现"
echo "✓ 采样器已集成"
echo "✓ 演示已更新"
echo "✓ 文档已完成"
echo "✓ 测试已通过"
echo ""

echo "📚 文档"
echo "======"
echo "• JSON_FORMAT_GUIDE.md - 详细使用指南"
echo "• DATA_INPUT_FORMAT_SUMMARY.md - 调整总结"
echo ""

echo "🚀 现在你可以:"
echo "✨ 直接使用 /data 目录下的真实数据"
echo "✨ 自动格式转换，无需手动处理"
echo "✨ 流式推送数据到采样器"
echo "✨ 完整集成到在线测试框架"
echo ""

echo "✅ 数据格式调整完成！"
